aws-region    = "us-east-1"
bucket-name   = "notification-system-project"
sns-name      = "notification-system-topic"
sns-email-sub = "cristobalgrau1+sns@gmail.com"
sqs-name      = "notification-system-sqs"